#!/bin/bash
if [[ -n "$1" && -e "$1" ]]
then
	list=($(<$1))
else
	list=($(</dev/stdin))
fi

[[ -z $list ]] && exit 1

temp=0
for i in ${list[@]}
do
	sum=$(calc -p -- $i+$temp)
	temp=$sum
done

[[ -n $sum ]] && echo "Sum: $sum"
